codecov:
  require_ci_to_pass: false

ignore:
  - "src/main.rs"

coverage:
  status:
    patch:
      default:
        informational: true
    project:
      default:
        informational: true
    default_rules:
      informational: true