//! Generate the native half of the shared Gate E portability corpus.
//!
//! The browser half is generated by `examples/browser/generate-gate-e-fixture.cjs`.
//! Both consume `tests/fixtures/gate_e/corpus.json` and must be regenerated
//! whenever its setup sequence changes.

#[cfg(target_arch = "wasm32")]
fn main() {}

#[cfg(not(target_arch = "wasm32"))]
fn main() -> anyhow::Result<()> {
    use minigraf::Minigraf;
    use serde::Deserialize;
    use std::path::PathBuf;

    #[derive(Deserialize)]
    struct Corpus {
        setup: Vec<Setup>,
    }

    #[derive(Deserialize)]
    struct Setup {
        datalog: String,
        checkpoint_after: bool,
    }

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let fixture_dir = root.join("tests/fixtures/gate_e");
    let corpus: Corpus = serde_json::from_slice(&std::fs::read(fixture_dir.join("corpus.json"))?)?;
    let destination = fixture_dir.join("native.graph");
    let staging = fixture_dir.join("native.next.graph");
    let _ = std::fs::remove_file(&staging);
    let _ = std::fs::remove_file(fixture_dir.join("native.next.graph.wal"));
    let _ = std::fs::remove_file(staging.with_extension("graph.lock"));

    {
        let db = Minigraf::open(&staging)?;
        for operation in corpus.setup {
            db.execute(&operation.datalog)?;
            if operation.checkpoint_after {
                db.checkpoint()?;
            }
        }
    }

    std::fs::rename(&staging, &destination)?;
    println!("Written: {}", destination.display());
    Ok(())
}
